### PR TITLE
Added `example` to `serenity.restart.browser.for.each` property values

### PR DESCRIPTION
**Pull request by amuradyan**
As seen on https://serenity-bdd.github.io/theserenitybook/latest/serenity-system-properties.html#_serenity_restart_browser_for_each.

### CODE REVIEW

**Comment by wakaleo** [comment]
Are you sure this option works?

**Comment by amuradyan** [comment]
Well, now that you've mentioned it I tested with all the values, and here is what I've got.

Given a scenario outline that has two examples
- Keywords `scenario`, `story`, `feature` and `never` work as expected and do not restart the browser per example
- `example` restarts the browser for each example, but so does `any_random_bunch_of_charachters`

Also, the browser restarts for each example when the `serenity.restart.browser.for.each` is not specified in `serenity.conf` at all.

I hope this helps.

**Comment by wakaleo** [comment]
Yes, restarting the browser is a real pain with Cucumber. I can point you to the code if you want to take a look at how it works.

**Comment by amuradyan** [comment]
Sure

**Comment by amuradyan** [comment]
Anyways, it seems from the tests that the `example` keyword is ignored so it should be removed from https://serenity-bdd.github.io/theserenitybook/latest/serenity-system-properties.html#_serenity_restart_browser_for_each. Is this correct? Should I update the pull request?

**Comment by wakaleo** [comment]
Yep

**Pull request merged**
