### PR TITLE
Issue#2252 serenity-core. Add description for serenity.full.page.screenshot.strategy property

### PR DESCRIPTION
**Pull request by daniilmatafonov**
I've added a description for the changes which were made in this [PR](https://github.com/serenity-bdd/serenity-core/pull/1975)

### CODE REVIEW

**Comment by preetimohan** [comment]
Is it possible to extend this feature to set the screenshot property at a specific serenity step rather than as a global parameter?

**Comment by globalworming** [comment]
sure, there should be no reason why this couldn't be annotation based like other screenshot controls. This has been requested more than once to when you want to propose a PR @preetimohan , people would be thankful

**Comment by wakaleo** [comment]
Have you tried using the @Screenshots annotation?

**Comment by globalworming** [comment]
it's about the full page or not. see https://github.com/serenity-bdd/serenity-core/issues/2252#issuecomment-760706348

**Comment by preetimohan** [comment]
> it's about the full page or not. see [serenity-bdd/serenity-core#2252 (comment)](https://github.com/serenity-bdd/serenity-core/issues/2252#issuecomment-760706348)

Yes actually what I need is more like @Screenshots(fullPage = true). This is because I run automation scripts mostly in Safari and full page screenshot will lead to elements going out of viewport. Then I will need to do a horizontal scroll to bring them back into viewport. I actually need full page screenshot only at a few specific steps

**Pull request merged**
